# SPDX-FileCopyrightText: 2024 Tobias Böhm <code@aibor.de>
#
# SPDX-License-Identifier: MIT

linters:
  enable-all: true
  disable:
    - depguard
    - err113
    - execinquery
    - exhaustruct
    - exportloopref
    - funlen
    - gomnd
    - paralleltest
    - varnamelen

linters-settings:
  exhaustive:
    default-signifies-exhaustive: true

  gosec:
    excludes:
      - G204

  nlreturn:
    block-size: 2

issues:
  include:
    - EXC0002
    - EXC0003
    - EXC0004
    - EXC0005
    - EXC0006
    - EXC0007
    - EXC0008
    - EXC0013
    - EXC0014

  exclude-rules:
    - linters:
        - errcheck
      source: "^\\s+defer \\S+\\.Close()"
