name: "Virtrun selftest"

inputs:
  kernel-version:
    description: "Kernel version to test with"
    required: true
  kernel-arch:
    description: "Kernel architecture to test with"
    required: true
  cmd:
    description: "Command to run. $KERNEL has the absolute path to the fetched kernel."
    required: true

runs:
  using: "docker"
  image: "Dockerfile"
  env:
    KERNEL_VER: ${{ inputs.kernel-version }}
    KERNEL_ARCH: ${{ inputs.kernel-arch }}
  args:
    - ${{ inputs.cmd }}
