# SPDX-FileCopyrightText: 2024 Tobias Böhm <code@aibor.de>
#
# SPDX-License-Identifier: MIT

name: "Virtrun selftest"

inputs:
  cmd:
    description: "Command to run."
    required: true

runs:
  using: "docker"
  image: "Dockerfile"
  entrypoint: "sh"
  args:
    - "-c"
    - ${{ inputs.cmd }}
