name: Test

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "main" ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint-and-test:
    name: Go lint and test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: ["~1.21", "~1.18"]
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-go@v3
        with:
          go-version: "${{ matrix.go-version }}"

      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: latest

      - name: Run go tests
        run: go test -race -v -cover -covermode=atomic ./...

  selftest:
    name: Run selftests
    runs-on: ubuntu-latest
    needs: lint-and-test
    strategy:
      matrix:
        version: ["6.6", "5.15"]
        arch: ["amd64", "arm64"]
        mode: ["wrapped", "standalone"]
    steps:
      - uses: actions/checkout@v3

      - uses: ./selftest
        env:
          GOARCH: "${{ matrix.arch }}"
        with:
          kernel-version: "${{ matrix.version }}"
          kernel-arch: "${{ matrix.arch }}"
          cmd: bash selftest/run_sysinit_test.sh ${{ matrix.mode }}
