name: Test

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "main" ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint-and-test:
    name: Go lint and test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: ["~1.21", "~1.20", "~1.19", "~1.18"]
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-go@v3
        with:
          go-version: "${{ matrix.go-version }}"

      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: latest

      - name: Run go tests
        run: go test -race ./...

  selftest:
    name: Run selftests
    runs-on: ubuntu-latest
    needs: lint-and-test
    strategy:
      matrix:
        version: ["6.6", "6.1", "5.15"]
        arch: ["amd64", "arm64"]
    env:
      QEMU_KERNEL: "${{ github.workspace }}/kernel/vmlinuz-${{ matrix.version}}-${{ matrix.arch }}"
      GOBIN: "${{ github.workspace }}/gobin"
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-go@v3
        with:
          go-version: '~1.18'

      - name: Install go tools and kernel
        run: |
          go install ./cmd/virtrun
          go install github.com/magefile/mage
          bash fetch_kernel.sh "${{ matrix.version }}" "${{ matrix.arch }}"

      - name: Install packages for selftest
        run: |
          sudo apt-get update
          if [[ "${{ matrix.arch }}" == amd64 ]]; then pkg=qemu-system-x86-microvm; else pkg=qemu-system-arm; fi
          sudo apt-get install -y --no-install-recommends $pkg

      - name: Run selftest wrapped
        if: "${{ matrix.version == 'amd64' }}"
        env:
          GOARCH: "${{ matrix.arch }}"
        run: $GOBIN/mage -v selftest 1 0 1

      - name: Run selftest standalone
        env:
          GOARCH: "${{ matrix.arch }}"
        run: $GOBIN/mage -v selftest 1 1 1
