name: Test

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "main" ]

jobs:
  go:
    name: Go lint and test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v3
        with:
          go-version: '1.21'

      - uses: actions/checkout@v3

      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: latest

      - name: Run go tests
        run: go test -race ./internal/... ./cmd/...

      - name: Install packages for selftest
        run: |
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends qemu-system-x86-microvm linux-image-generic
          sudo chmod go+r /boot/vmlinuz-*

      - name: Run selftest wrapped
        env:
          QEMU_KERNEL: /boot/vmlinuz
        run: go run github.com/magefile/mage selftest 0 0 1

      - name: Run selftest standalone
        env:
          QEMU_KERNEL: /boot/vmlinuz
        run: go run github.com/magefile/mage selftest 0 1 1
