# SPDX-FileCopyrightText: 2024 Tobias Böhm <code@aibor.de>
#
# SPDX-License-Identifier: MIT

name: Test

on:
  push:
    branches: [ "**" ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint-and-test:
    name: Go lint and test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.22.x"
          cache: false

      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: latest

      - name: Run vet with all constraints
        run: go vet -tags integration,integration_guest,standalone ./...

      - name: Run go tests
        run: go test -race -v -cover -covermode=atomic ./...

  integration-tests:
    name: Run integration tests
    runs-on: ubuntu-latest
    needs:
      - lint-and-test
    strategy:
      matrix:
        kernel_version:
          - "6.7"
          - "6.6"
          - "6.1"
        kernel_arch:
          - "amd64"
        include:
          - kernel_version: "6.7"
            kernel_arch: "arm64"
    env:
      KERNELVERSION: "${{ matrix.kernel_version }}"
      KERNELARCH: "${{ matrix.kernel_arch }}"
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Fetch kernel
        env:
          CONTAINERBIN: docker
        run: |
          ./integrationtesting/fetch_kernel.sh ${{ env.KERNELVERSION }} ${{ env.KERNELARCH }} "${{ github.workspace }}/vmlinuz"

      - name: Run tests
        uses: ./integrationtesting
        with:
          cmd: |
            go test -race -v -tags integration ./integrationtesting/ \
              -kernel.path "/github/workspace/vmlinuz" \
              -kernel.arch ${{ env.KERNELARCH }}

  reuse-lint:
    name: FSFE REUSE Compliance Check
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: REUSE Compliance Check
      uses: fsfe/reuse-action@v3

  results:
    if: always()
    runs-on: ubuntu-latest
    name: Test Results
    needs:
    - lint-and-test
    - integration-tests
    - reuse-lint
    steps:
    - run: exit 1
      if: |
        contains(needs.*.result, 'failure') ||
          contains(needs.*.result, 'cancelled')
