name: Test

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "main" ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint-and-test:
    name: Go lint and test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.21.x"

      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: latest

      - name: Run vet with all constraints
        run: go vet -tags integration,integration_guest,standalone ./...

      - name: Run go tests
        run: go test -race -v -cover -covermode=atomic ./...

  integration-tests:
    name: Run integration tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Ensure kernel dir exists
        run: mkdir -p ./integrationtesting/kernels

      - name: Run tests
        uses: ./integrationtesting
        with:
          cmd: go test -race -v -tags integration ./integrationtesting/ 
