# SPDX-FileCopyrightText: 2024 Tobias Böhm <code@aibor.de>
#
# SPDX-License-Identifier: MIT

name: Test

on:
  push:
    branches: [ "**" ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint-and-test:
    name: Go lint and test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.22.x"
          cache: false

      - name: Run go generate
        run: go generate -v ./...

      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: latest

      - name: Run vet with all constraints
        run: go vet -tags integration,integration_guest,standalone ./...

      - name: Run go tests
        run: go test -race -v -cover -covermode=atomic ./...

  integration-tests:
    name: Run integration tests
    runs-on: ubuntu-latest
    needs:
      - lint-and-test
    strategy:
      matrix:
        kernel_version:
          - "6.9"
          - "6.6"
          - "6.1"
        kernel_arch:
          - "amd64"
        include:
          - kernel_version: "6.9"
            kernel_arch: "arm64"
    env:
      KERNELVERSION: "${{ matrix.kernel_version }}"
      KERNELARCH: "${{ matrix.kernel_arch }}"
      GOCOVERDIR: "${{ github.workspace }}/gocoverdir"
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Create gocoverdir
        run: mkdir "${{ env.GOCOVERDIR }}"

      - name: Fetch kernel
        env:
          CONTAINERBIN: docker
        run: |
          ./testing/fetch_kernel.sh ${{ env.KERNELVERSION }} ${{ env.KERNELARCH }} "${{ github.workspace }}/vmlinuz"

      - name: Run tests
        uses: ./testing
        with:
          cmd: |
            go generate -v -tags integration ./...
            go test -race -v -tags integration ./testing/ \
              -kernel.path "/github/workspace/vmlinuz" \
              -kernel.arch ${{ env.KERNELARCH }}

      - name: Run covdata
        run: go tool covdata percent -i "${{ env.GOCOVERDIR }}"

  integration-tests-modules:
    name: Run integration tests for kernel modules
    runs-on: ubuntu-latest
    needs:
      - lint-and-test
    env:
      GOCOVERDIR: "${{ github.workspace }}/gocoverdir"
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Create gocoverdir
        run: mkdir "${{ env.GOCOVERDIR }}"

      - name: Run module test
        uses: ./testing
        with:
          cmd: |
            apk add linux-virt
            ln -s /lib/modules/*/kernel /lib/modules/
            go generate -v -tags integration ./...
            go test -race -v -tags integration ./testing/ \
              -kernel.path "/boot/vmlinuz-virt" \
              -kernel.arch amd64 \
              -kernel.module /lib/modules/kernel/drivers/net/tun.ko.gz \
              -kernel.module /lib/modules/kernel/drivers/net/veth.ko.gz \
              -run TestGuestSysinit

      - name: Run covdata
        run: go tool covdata percent -i "${{ env.GOCOVERDIR }}"

  reuse-lint:
    name: FSFE REUSE Compliance Check
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: REUSE Compliance Check
      uses: fsfe/reuse-action@v4

  results:
    if: always()
    runs-on: ubuntu-latest
    name: Test Results
    needs:
    - lint-and-test
    - integration-tests
    - integration-tests-modules
    - reuse-lint
    steps:
    - run: exit 1
      if: |
        contains(needs.*.result, 'failure') ||
          contains(needs.*.result, 'cancelled')
